apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movieapp
  template:
    metadata:
      labels:
        app: movieapp
    spec:
      containers:
      - name: movieapp
        image: rudrappan/movieapp:latest   # initial image
        ports:
        - containerPort: 80
