apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: movie-eks-cluster
  region: ap-south-1
  version: "1.32"

iam:
  withOIDC: true

managedNodeGroups:
  - name: movie-workers
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    ssh:
      allow: false

vpc:
  nat:
    gateway: Single
